config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  get 'todolists' => 'todolists#index'
  get 'todolists/new' => 'todolists#new', as: 'todolist_new'
  post 'todolists' => 'todolists#create'
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    # attachment :image
    has_one_attached :image
    validates :title, presence: true
    validates :body, presence: true
    validate :image_type

    private
    def image_type
        if !image.blob.content_type.in?(%('image/jpeg image/png))
            image.purge
            errors.add(:image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
    end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
    def index
        @lists = List.all
    end
    def new
        @list = List.new
    end
    def create
        @list = List.new(listparams)
        # byebug
        if @list.save
            redirect_to todolists_path
        else
            render :new
        end
    end
    def show
        @list = List.find(params[:id])
    end
    def edit
        @list = List.find(params[:id])
    end
    def update
        list = List.find(params[:id])
        list.update(listparams)
        redirect_to todolist_path(list.id)
    end
    def destroy
        list = List.find(params[:id])
        list.destroy
        redirect_to todolists_path
    end

    private
    def listparams
        params.require(:list).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>This is Top page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="headline"> All Lists</h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "TodoLists", todolists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", todolist_new_path %>
        </li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<!--<%= debug @list %>-->
    <!--<%= @list.inspect %>-->
<%= form_with model: @list, url: "/todolists/#{@list.id}", local:true do |f| %>
    <h2>タイトル</h2>
    <%= f.text_field :title %>
    <h2>本文</h2>
    <%= f.text_field :body %>
    <%= f.file_field :image %>
    <%= f.submit '更新' %>
<% end %>

app/views/todolists/index.html.erb
<div class="list-wrap">
    <% @lists.each do |list| %>
        <div class="list-box">
            <% if list.image.attached? %>
                <%= image_tag list.image.variant(resize:'300x300') %>
            <% else %>
                <%= image_tag 'no_image.png', size: '300x300', alt: "no_image" %>
            <% end %>
            <div class="list-comment">
                <span class="list-body"><%= list.body %></span>
                <span class="list-title"><%= link_to list.title, todolist_path(list.id) %></span>
            </div>
        </div>
    <% end %>
</div>

app/views/todolists/new.html.erb
<h1>投稿画面</h1>
<% if @list.errors.any? %>
    <%= @list.errors.count %>件のエラーが発生しました。
    <% @list.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>
<%= form_with model:@list, url:'/todolists', local:true do |f| %>
    <h2>タイトル</h2>
    <%= f.text_field :title %>
    <h2>本文</h2>
    <%= f.text_field :body %>
    <%= f.file_field :image %>
    <%= f.submit '投稿' %>
<% end %>

app/views/todolists/show.html.erb
<h1>詳細表示</h1>
<h2>本文</h2>
<p><%= @list.title %></p>
<h2>投稿</h2>
<p><%= @list.body %></p>
            <% if @list.image.attached? %>
                <%= image_tag @list.image.variant(resize:'300x300') %>
            <% else %>
                <%= image_tag 'no_image.png', size: '300x300', alt: "no_image" %>
            <% end %>
<p><%= link_to 'EDIT', edit_todolist_path %></p>
<p><%= link_to 'DELETE', destroy_todolist_path(@list.id), method: :delete %></p>
<p><%= link_to 'INDEX', todolists_path %></p>